# Generated by Django 3.0.6 on 2020-05-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200511_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='breed',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
